name: Notify Discord

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      message:
        required: true
        type: string
    secrets:
      DISCORD_WEBHOOK:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Discord
        env:
          TITLE: ${{ inputs.title }}
          MESSAGE: ${{ inputs.message }}
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST "$WEBHOOK" \
          -H "Content-Type: application/json" \
          -d "{\"embeds\": [{\"title\": \"$TITLE\", \"description\": \"$MESSAGE\"}]}"
